-- AlterTable
ALTER TABLE "Expense" ALTER COLUMN "mileage" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "MileageRecord" ALTER COLUMN "mileage" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "Reminder" ALTER COLUMN "dueMileage" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "intervalMileage" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "vehicles" ALTER COLUMN "mileage" SET DATA TYPE DOUBLE PRECISION;
