// Dados mockados da FIPE para uso no frontend
export interface MockBrand {
    codigo: string;
    nome: string;
}

export interface MockModel {
    codigo: string;
    nome: string;
}

export interface MockYear {
    codigo: string;
    nome: string;
}

export const MOCK_BRANDS: MockBrand[] = [
    { codigo: '1', nome: 'Acura' },
    { codigo: '2', nome: 'Agrale' },
    { codigo: '3', nome: 'Alfa Romeo' },
    { codigo: '4', nome: 'Aston Martin' },
    { codigo: '5', nome: 'Audi' },
    { codigo: '6', nome: 'Bentley' },
    { codigo: '7', nome: 'BMW' },
    { codigo: '8', nome: 'Buick' },
    { codigo: '9', nome: 'Cadillac' },
    { codigo: '10', nome: 'Chevrolet' },
    { codigo: '11', nome: 'Chrysler' },
    { codigo: '12', nome: 'Citroën' },
    { codigo: '13', nome: 'Dodge' },
    { codigo: '14', nome: 'Ferrari' },
    { codigo: '15', nome: 'Fiat' },
    { codigo: '16', nome: 'Ford' },
    { codigo: '17', nome: 'Honda' },
    { codigo: '18', nome: 'Hyundai' },
    { codigo: '19', nome: 'Infiniti' },
    { codigo: '20', nome: 'Jaguar' },
    { codigo: '21', nome: 'Jeep' },
    { codigo: '22', nome: 'Kia' },
    { codigo: '23', nome: 'Lamborghini' },
    { codigo: '24', nome: 'Land Rover' },
    { codigo: '25', nome: 'Lexus' },
    { codigo: '26', nome: 'Maserati' },
    { codigo: '27', nome: 'Mazda' },
    { codigo: '28', nome: 'Mercedes-Benz' },
    { codigo: '29', nome: 'Mini' },
    { codigo: '30', nome: 'Mitsubishi' },
    { codigo: '31', nome: 'Nissan' },
    { codigo: '32', nome: 'Peugeot' },
    { codigo: '33', nome: 'Porsche' },
    { codigo: '34', nome: 'Ram' },
    { codigo: '35', nome: 'Renault' },
    { codigo: '36', nome: 'Rolls-Royce' },
    { codigo: '37', nome: 'Subaru' },
    { codigo: '38', nome: 'Suzuki' },
    { codigo: '39', nome: 'Toyota' },
    { codigo: '40', nome: 'Volkswagen' },
    { codigo: '41', nome: 'Volvo' }
];

export const MOCK_MODELS: { [brandCode: string]: MockModel[] } = {
    '10': [ // Chevrolet
        { codigo: '101', nome: 'Agile' },
        { codigo: '102', nome: 'Astra' },
        { codigo: '103', nome: 'Blazer' },
        { codigo: '104', nome: 'Celta' },
        { codigo: '105', nome: 'Classic' },
        { codigo: '106', nome: 'Cobalt' },
        { codigo: '107', nome: 'Corsa' },
        { codigo: '108', nome: 'Cruze' },
        { codigo: '109', nome: 'Malibu' },
        { codigo: '110', nome: 'Onix' },
        { codigo: '111', nome: 'Prisma' },
        { codigo: '112', nome: 'S10' },
        { codigo: '113', nome: 'Spin' },
        { codigo: '114', nome: 'Tracker' },
        { codigo: '115', nome: 'Vectra' }
    ],
    '16': [ // Ford
        { codigo: '161', nome: 'EcoSport' },
        { codigo: '162', nome: 'Edge' },
        { codigo: '163', nome: 'Escort' },
        { codigo: '164', nome: 'Fiesta' },
        { codigo: '165', nome: 'Focus' },
        { codigo: '166', nome: 'Fusion' },
        { codigo: '167', nome: 'Ka' },
        { codigo: '168', nome: 'Mondeo' },
        { codigo: '169', nome: 'Ranger' },
        { codigo: '170', nome: 'Territory' }
    ],
    '15': [ // Fiat
        { codigo: '151', nome: 'Argo' },
        { codigo: '152', nome: 'Bravo' },
        { codigo: '153', nome: 'Cronos' },
        { codigo: '154', nome: 'Doblo' },
        { codigo: '155', nome: 'Fiorino' },
        { codigo: '156', nome: 'Grand Siena' },
        { codigo: '157', nome: 'Idea' },
        { codigo: '158', nome: 'Linea' },
        { codigo: '159', nome: 'Marea' },
        { codigo: '160', nome: 'Mobi' },
        { codigo: '161', nome: 'Palio' },
        { codigo: '162', nome: 'Pulse' },
        { codigo: '163', nome: 'Strada' },
        { codigo: '164', nome: 'Toro' },
        { codigo: '165', nome: 'Uno' },
        { codigo: '166', nome: 'Weekend' },
        { codigo: '167', nome: 'Punto' },
        { codigo: '168', nome: 'Siena' },
        { codigo: '169', nome: 'Palio Weekend' },
        { codigo: '170', nome: 'Ducato' },
        { codigo: '171', nome: 'Scudo' },
        { codigo: '172', nome: 'Ulysse' },
        { codigo: '173', nome: 'Multipla' },
        { codigo: '174', nome: 'Stilo' },
        { codigo: '175', nome: 'Albea' }
    ],
    '40': [ // Volkswagen
        { codigo: '401', nome: 'Amarok' },
        { codigo: '402', nome: 'Bora' },
        { codigo: '403', nome: 'Caddy' },
        { codigo: '404', nome: 'Crossfox' },
        { codigo: '405', nome: 'Fox' },
        { codigo: '406', nome: 'Fusca' },
        { codigo: '407', nome: 'Gol' },
        { codigo: '408', nome: 'Jetta' },
        { codigo: '409', nome: 'Kombi' },
        { codigo: '410', nome: 'Nivus' },
        { codigo: '411', nome: 'Passat' },
        { codigo: '412', nome: 'Polo' },
        { codigo: '413', nome: 'Saveiro' },
        { codigo: '414', nome: 'Spacefox' },
        { codigo: '415', nome: 'T-Cross' },
        { codigo: '416', nome: 'Tiguan' },
        { codigo: '417', nome: 'Touareg' },
        { codigo: '418', nome: 'Up!' },
        { codigo: '419', nome: 'Virtus' },
        { codigo: '420', nome: 'Voyage' }
    ],
    '39': [ // Toyota
        { codigo: '391', nome: 'Camry' },
        { codigo: '392', nome: 'Corolla' },
        { codigo: '393', nome: 'Etios' },
        { codigo: '394', nome: 'Hilux' },
        { codigo: '395', nome: 'Prius' },
        { codigo: '396', nome: 'SW4' },
        { codigo: '397', nome: 'Yaris' }
    ],
    '17': [ // Honda
        { codigo: '171', nome: 'City' },
        { codigo: '172', nome: 'Civic' },
        { codigo: '173', nome: 'CR-V' },
        { codigo: '174', nome: 'Fit' },
        { codigo: '175', nome: 'HR-V' },
        { codigo: '176', nome: 'WR-V' }
    ],
    '7': [ // BMW
        { codigo: '71', nome: 'Série 1' },
        { codigo: '72', nome: 'Série 3' },
        { codigo: '73', nome: 'Série 5' },
        { codigo: '74', nome: 'Série 7' },
        { codigo: '75', nome: 'X1' },
        { codigo: '76', nome: 'X3' },
        { codigo: '77', nome: 'X5' },
        { codigo: '78', nome: 'X6' }
    ],
    '28': [ // Mercedes-Benz
        { codigo: '281', nome: 'Classe A' },
        { codigo: '282', nome: 'Classe B' },
        { codigo: '283', nome: 'Classe C' },
        { codigo: '284', nome: 'Classe E' },
        { codigo: '285', nome: 'Classe S' },
        { codigo: '286', nome: 'GLA' },
        { codigo: '287', nome: 'GLC' },
        { codigo: '288', nome: 'GLE' },
        { codigo: '289', nome: 'GLS' }
    ],
    '5': [ // Audi
        { codigo: '51', nome: 'A1' },
        { codigo: '52', nome: 'A3' },
        { codigo: '53', nome: 'A4' },
        { codigo: '54', nome: 'A5' },
        { codigo: '55', nome: 'A6' },
        { codigo: '56', nome: 'A7' },
        { codigo: '57', nome: 'A8' },
        { codigo: '58', nome: 'Q3' },
        { codigo: '59', nome: 'Q5' },
        { codigo: '510', nome: 'Q7' },
        { codigo: '511', nome: 'Q8' },
        { codigo: '512', nome: 'TT' }
    ],
    '18': [ // Hyundai
        { codigo: '181', nome: 'Accent' },
        { codigo: '182', nome: 'Azera' },
        { codigo: '183', nome: 'Creta' },
        { codigo: '184', nome: 'Elantra' },
        { codigo: '185', nome: 'HB20' },
        { codigo: '186', nome: 'HB20S' },
        { codigo: '187', nome: 'i30' },
        { codigo: '188', nome: 'Santa Fe' },
        { codigo: '189', nome: 'Sonata' },
        { codigo: '190', nome: 'Tucson' },
        { codigo: '191', nome: 'Veloster' }
    ],
    '22': [ // Kia
        { codigo: '221', nome: 'Besta' },
        { codigo: '222', nome: 'Carens' },
        { codigo: '223', nome: 'Cerato' },
        { codigo: '224', nome: 'Morning' },
        { codigo: '225', nome: 'New Sportage' },
        { codigo: '226', nome: 'Optima' },
        { codigo: '227', nome: 'Picanto' },
        { codigo: '228', nome: 'Rio' },
        { codigo: '229', nome: 'Sorento' },
        { codigo: '230', nome: 'Soul' },
        { codigo: '231', nome: 'Sportage' }
    ],
    '31': [ // Nissan
        { codigo: '311', nome: '350Z' },
        { codigo: '312', nome: '370Z' },
        { codigo: '313', nome: 'Altima' },
        { codigo: '314', nome: 'Frontier' },
        { codigo: '315', nome: 'GT-R' },
        { codigo: '316', nome: 'Kicks' },
        { codigo: '317', nome: 'Leaf' },
        { codigo: '318', nome: 'March' },
        { codigo: '319', nome: 'Maxima' },
        { codigo: '320', nome: 'Murano' },
        { codigo: '321', nome: 'Sentra' },
        { codigo: '322', nome: 'Tiida' },
        { codigo: '323', nome: 'Versa' },
        { codigo: '324', nome: 'X-Trail' }
    ],
    '35': [ // Renault
        { codigo: '351', nome: 'Captur' },
        { codigo: '352', nome: 'Clio' },
        { codigo: '353', nome: 'Duster' },
        { codigo: '354', nome: 'Fluence' },
        { codigo: '355', nome: 'Kangoo' },
        { codigo: '356', nome: 'Kwid' },
        { codigo: '357', nome: 'Logan' },
        { codigo: '358', nome: 'Master' },
        { codigo: '359', nome: 'Megane' },
        { codigo: '360', nome: 'Oroch' },
        { codigo: '361', nome: 'Sandero' },
        { codigo: '362', nome: 'Scenic' },
        { codigo: '363', nome: 'Symbol' },
        { codigo: '364', nome: 'Talisman' }
    ],
    '21': [ // Jeep
        { codigo: '211', nome: 'Cherokee' },
        { codigo: '212', nome: 'Compass' },
        { codigo: '213', nome: 'Gladiator' },
        { codigo: '214', nome: 'Grand Cherokee' },
        { codigo: '215', nome: 'Renegade' },
        { codigo: '216', nome: 'Wrangler' }
    ],
    '30': [ // Mitsubishi
        { codigo: '301', nome: 'ASX' },
        { codigo: '302', nome: 'Eclipse Cross' },
        { codigo: '303', nome: 'L200' },
        { codigo: '304', nome: 'Lancer' },
        { codigo: '305', nome: 'Outlander' },
        { codigo: '306', nome: 'Pajero' },
        { codigo: '307', nome: 'Pajero Sport' }
    ],
    '37': [ // Subaru
        { codigo: '371', nome: 'BRZ' },
        { codigo: '372', nome: 'Forester' },
        { codigo: '373', nome: 'Impreza' },
        { codigo: '374', nome: 'Legacy' },
        { codigo: '375', nome: 'Outback' },
        { codigo: '376', nome: 'XV' }
    ],
    '38': [ // Suzuki
        { codigo: '381', nome: 'Baleno' },
        { codigo: '382', nome: 'Celerio' },
        { codigo: '383', nome: 'Grand Vitara' },
        { codigo: '384', nome: 'Ignis' },
        { codigo: '385', nome: 'Jimny' },
        { codigo: '386', nome: 'S-Cross' },
        { codigo: '387', nome: 'Swift' },
        { codigo: '388', nome: 'Vitara' }
    ],
    '1': [ // Acura
        { codigo: '11', nome: 'MDX' },
        { codigo: '12', nome: 'RDX' },
        { codigo: '13', nome: 'TLX' },
        { codigo: '14', nome: 'ILX' },
        { codigo: '15', nome: 'RLX' },
        { codigo: '16', nome: 'NSX' },
        { codigo: '17', nome: 'Integra' },
        { codigo: '18', nome: 'Legend' },
        { codigo: '19', nome: 'Vigor' },
        { codigo: '20', nome: 'CL' },
        { codigo: '21', nome: 'TL' },
        { codigo: '22', nome: 'TSX' },
        { codigo: '23', nome: 'RSX' },
        { codigo: '24', nome: 'ZDX' },
        { codigo: '25', nome: 'SLX' }
    ],
    '2': [ // Agrale
        { codigo: '21', nome: 'MARRUÁ' },
        { codigo: '22', nome: 'AMAZONAS' },
        { codigo: '23', nome: 'TROPICAL' },
        { codigo: '24', nome: 'CHAMAS' },
        { codigo: '25', nome: 'STAR' },
        { codigo: '26', nome: 'WORKER' },
        { codigo: '27', nome: 'RURAL' },
        { codigo: '28', nome: 'CITY' },
        { codigo: '29', nome: 'METROPOLIS' },
        { codigo: '30', nome: 'TIGER' }
    ],
    '3': [ // Alfa Romeo
        { codigo: '31', nome: 'Giulia' },
        { codigo: '32', nome: 'Stelvio' },
        { codigo: '33', nome: 'Tonale' },
        { codigo: '34', nome: 'Giulietta' },
        { codigo: '35', nome: 'MiTo' },
        { codigo: '36', nome: '4C' },
        { codigo: '37', nome: '8C' },
        { codigo: '38', nome: 'Brera' },
        { codigo: '39', nome: 'Spider' },
        { codigo: '40', nome: '159' },
        { codigo: '41', nome: '147' },
        { codigo: '42', nome: '156' },
        { codigo: '43', nome: '166' },
        { codigo: '44', nome: 'GTV' },
        { codigo: '45', nome: 'GT' }
    ],
    '4': [ // Aston Martin
        { codigo: '41', nome: 'DB11' },
        { codigo: '42', nome: 'DBX' },
        { codigo: '43', nome: 'Vantage' },
        { codigo: '44', nome: 'DBS' },
        { codigo: '45', nome: 'Valkyrie' },
        { codigo: '46', nome: 'DB9' },
        { codigo: '47', nome: 'DB7' },
        { codigo: '48', nome: 'Vanquish' },
        { codigo: '49', nome: 'Rapide' },
        { codigo: '50', nome: 'One-77' },
        { codigo: '51', nome: 'Cygnet' },
        { codigo: '52', nome: 'Vulcan' },
        { codigo: '53', nome: 'V8 Vantage' },
        { codigo: '54', nome: 'DB5' },
        { codigo: '55', nome: 'DB6' }
    ],
    '6': [ // Bentley
        { codigo: '61', nome: 'Continental GT' },
        { codigo: '62', nome: 'Bentayga' },
        { codigo: '63', nome: 'Flying Spur' },
        { codigo: '64', nome: 'Mulliner' },
        { codigo: '65', nome: 'Arnage' },
        { codigo: '66', nome: 'Azure' },
        { codigo: '67', nome: 'Brooklands' },
        { codigo: '68', nome: 'Continental' },
        { codigo: '69', nome: 'Turbo R' },
        { codigo: '70', nome: 'Mulsanne' },
        { codigo: '71', nome: 'Eight' },
        { codigo: '72', nome: 'T' },
        { codigo: '73', nome: 'S' },
        { codigo: '74', nome: 'R' },
        { codigo: '75', nome: 'Speed' }
    ],
    '8': [ // Buick
        { codigo: '81', nome: 'Enclave' },
        { codigo: '82', nome: 'Encore' },
        { codigo: '83', nome: 'Envision' },
        { codigo: '84', nome: 'LaCrosse' },
        { codigo: '85', nome: 'Regal' },
        { codigo: '86', nome: 'Verano' },
        { codigo: '87', nome: 'Cascada' },
        { codigo: '88', nome: 'Riviera' },
        { codigo: '89', nome: 'Roadmaster' },
        { codigo: '90', nome: 'Skylark' },
        { codigo: '91', nome: 'Century' },
        { codigo: '92', nome: 'LeSabre' },
        { codigo: '93', nome: 'Park Avenue' },
        { codigo: '94', nome: 'Electra' },
        { codigo: '95', nome: 'Special' }
    ],
    '9': [ // Cadillac
        { codigo: '91', nome: 'CT4' },
        { codigo: '92', nome: 'CT5' },
        { codigo: '93', nome: 'CT6' },
        { codigo: '94', nome: 'XT4' },
        { codigo: '95', nome: 'XT5' },
        { codigo: '96', nome: 'XT6' },
        { codigo: '97', nome: 'Escalade' },
        { codigo: '98', nome: 'ATS' },
        { codigo: '99', nome: 'CTS' },
        { codigo: '100', nome: 'XTS' },
        { codigo: '101', nome: 'SRX' },
        { codigo: '102', nome: 'DeVille' },
        { codigo: '103', nome: 'Seville' },
        { codigo: '104', nome: 'Eldorado' },
        { codigo: '105', nome: 'Fleetwood' },
        { codigo: '106', nome: 'Brougham' },
        { codigo: '107', nome: 'Cimarron' },
        { codigo: '108', nome: 'Allanté' },
        { codigo: '109', nome: 'Catera' }
    ],
    '11': [ // Chrysler
        { codigo: '111', nome: '300C' },
        { codigo: '112', nome: 'Pacifica' },
        { codigo: '113', nome: 'Voyager' },
        { codigo: '114', nome: 'Aspen' },
        { codigo: '115', nome: 'Sebring' },
        { codigo: '116', nome: 'PT Cruiser' },
        { codigo: '117', nome: 'Crossfire' },
        { codigo: '118', nome: 'Concorde' },
        { codigo: '119', nome: 'LHS' },
        { codigo: '120', nome: 'New Yorker' },
        { codigo: '121', nome: 'Imperial' },
        { codigo: '122', nome: 'LeBaron' },
        { codigo: '123', nome: 'Fifth Avenue' },
        { codigo: '124', nome: 'E-Class' },
        { codigo: '125', nome: 'Town & Country' }
    ],
    '12': [ // Citroën
        { codigo: '121', nome: 'C3' },
        { codigo: '122', nome: 'C4' },
        { codigo: '123', nome: 'C5' },
        { codigo: '124', nome: 'C6' },
        { codigo: '125', nome: 'C-Elysee' },
        { codigo: '126', nome: 'Berlingo' },
        { codigo: '127', nome: 'C3 Aircross' },
        { codigo: '128', nome: 'C4 Cactus' },
        { codigo: '129', nome: 'C4 Picasso' },
        { codigo: '130', nome: 'C5 Aircross' },
        { codigo: '131', nome: 'C1' },
        { codigo: '132', nome: 'C2' },
        { codigo: '133', nome: 'C3 Picasso' },
        { codigo: '134', nome: 'C4 Grand Picasso' },
        { codigo: '135', nome: 'C8' },
        { codigo: '136', nome: 'DS3' },
        { codigo: '137', nome: 'DS4' },
        { codigo: '138', nome: 'DS5' },
        { codigo: '139', nome: 'Jumpy' },
        { codigo: '140', nome: 'Jumper' }
    ],
    '13': [ // Dodge
        { codigo: '131', nome: 'Challenger' },
        { codigo: '132', nome: 'Charger' },
        { codigo: '133', nome: 'Durango' },
        { codigo: '134', nome: 'Journey' },
        { codigo: '135', nome: 'Grand Caravan' },
        { codigo: '136', nome: 'Dart' },
        { codigo: '137', nome: 'Avenger' },
        { codigo: '138', nome: 'Caliber' },
        { codigo: '139', nome: 'Nitro' },
        { codigo: '140', nome: 'Magnum' },
        { codigo: '141', nome: 'Stratus' },
        { codigo: '142', nome: 'Neon' },
        { codigo: '143', nome: 'Intrepid' },
        { codigo: '144', nome: 'Stealth' },
        { codigo: '145', nome: 'Viper' },
        { codigo: '146', nome: 'Ram' },
        { codigo: '147', nome: 'Dakota' },
        { codigo: '148', nome: 'Caravan' },
        { codigo: '149', nome: 'Shadow' },
        { codigo: '150', nome: 'Spirit' }
    ],
    '14': [ // Ferrari
        { codigo: '141', nome: 'F8 Tributo' },
        { codigo: '142', nome: 'SF90 Stradale' },
        { codigo: '143', nome: '812 Superfast' },
        { codigo: '144', nome: 'Roma' },
        { codigo: '145', nome: 'Portofino' },
        { codigo: '146', nome: 'F12' },
        { codigo: '147', nome: 'FF' },
        { codigo: '148', nome: 'F430' },
        { codigo: '149', nome: '360' },
        { codigo: '150', nome: 'F355' },
        { codigo: '151', nome: '348' },
        { codigo: '152', nome: 'Testarossa' },
        { codigo: '153', nome: '512' },
        { codigo: '154', nome: '308' },
        { codigo: '155', nome: 'Dino' },
        { codigo: '156', nome: '250' },
        { codigo: '157', nome: 'F40' },
        { codigo: '158', nome: 'F50' },
        { codigo: '159', nome: 'Enzo' },
        { codigo: '160', nome: 'LaFerrari' },
        { codigo: '161', nome: 'FXX' },
        { codigo: '162', nome: '599' },
        { codigo: '163', nome: '612' },
        { codigo: '164', nome: 'California' },
        { codigo: '165', nome: '458' },
        { codigo: '166', nome: '488' },
        { codigo: '167', nome: 'GTC4Lusso' },
        { codigo: '168', nome: 'Monza' },
        { codigo: '169', nome: 'Daytona SP3' }
    ],
    '19': [ // Infiniti
        { codigo: '191', nome: 'Q50' },
        { codigo: '192', nome: 'Q60' },
        { codigo: '193', nome: 'Q70' },
        { codigo: '194', nome: 'QX30' },
        { codigo: '195', nome: 'QX50' },
        { codigo: '196', nome: 'QX60' },
        { codigo: '197', nome: 'QX70' },
        { codigo: '198', nome: 'QX80' },
        { codigo: '199', nome: 'G37' },
        { codigo: '200', nome: 'G35' },
        { codigo: '201', nome: 'M' },
        { codigo: '202', nome: 'EX' },
        { codigo: '203', nome: 'FX' },
        { codigo: '204', nome: 'JX' },
        { codigo: '205', nome: 'I' },
        { codigo: '206', nome: 'Q' },
        { codigo: '207', nome: 'Q45' },
        { codigo: '208', nome: 'G20' },
        { codigo: '209', nome: 'G25' },
        { codigo: '210', nome: 'M25' },
        { codigo: '211', nome: 'M35' },
        { codigo: '212', nome: 'M45' },
        { codigo: '213', nome: 'M56' },
        { codigo: '214', nome: 'Q30' },
        { codigo: '215', nome: 'Q40' },
        { codigo: '216', nome: 'Q70L' }
    ],
    '20': [ // Jaguar
        { codigo: '201', nome: 'F-Type' },
        { codigo: '202', nome: 'XE' },
        { codigo: '203', nome: 'XF' },
        { codigo: '204', nome: 'XJ' },
        { codigo: '205', nome: 'F-Pace' },
        { codigo: '206', nome: 'E-Pace' },
        { codigo: '207', nome: 'I-Pace' },
        { codigo: '208', nome: 'XK' },
        { codigo: '209', nome: 'X-Type' },
        { codigo: '210', nome: 'S-Type' },
        { codigo: '211', nome: 'XJR' },
        { codigo: '212', nome: 'XKR' },
        { codigo: '213', nome: 'F-Type R' },
        { codigo: '214', nome: 'XFR' },
        { codigo: '215', nome: 'XKR-S' },
        { codigo: '216', nome: 'XJ220' },
        { codigo: '217', nome: 'E-Type' },
        { codigo: '218', nome: 'XJS' },
        { codigo: '219', nome: 'XJ6' },
        { codigo: '220', nome: 'XJ12' },
        { codigo: '221', nome: 'Mark 2' },
        { codigo: '222', nome: 'XK120' },
        { codigo: '223', nome: 'XK140' },
        { codigo: '224', nome: 'XK150' },
        { codigo: '225', nome: 'C-Type' },
        { codigo: '226', nome: 'D-Type' }
    ],
    '23': [ // Lamborghini
        { codigo: '231', nome: 'Huracán' },
        { codigo: '232', nome: 'Aventador' },
        { codigo: '233', nome: 'Urus' },
        { codigo: '234', nome: 'Revuelto' },
        { codigo: '235', nome: 'Gallardo' },
        { codigo: '236', nome: 'Murciélago' },
        { codigo: '237', nome: 'Diablo' },
        { codigo: '238', nome: 'Countach' },
        { codigo: '239', nome: 'Jalpa' },
        { codigo: '240', nome: 'Urraco' },
        { codigo: '241', nome: 'Espada' },
        { codigo: '242', nome: 'Islero' },
        { codigo: '243', nome: 'Jarama' },
        { codigo: '244', nome: 'Miura' },
        { codigo: '245', nome: '350GT' },
        { codigo: '246', nome: '400GT' },
        { codigo: '247', nome: 'Reventón' },
        { codigo: '248', nome: 'Sesto Elemento' },
        { codigo: '249', nome: 'Veneno' },
        { codigo: '250', nome: 'Centenario' },
        { codigo: '251', nome: 'Sián' },
        { codigo: '252', nome: 'Essenza SCV12' },
        { codigo: '253', nome: 'Countach LPI 800-4' }
    ],
    '24': [ // Land Rover
        { codigo: '241', nome: 'Range Rover' },
        { codigo: '242', nome: 'Range Rover Sport' },
        { codigo: '243', nome: 'Range Rover Velar' },
        { codigo: '244', nome: 'Range Rover Evoque' },
        { codigo: '245', nome: 'Discovery' },
        { codigo: '246', nome: 'Discovery Sport' },
        { codigo: '247', nome: 'Defender' },
        { codigo: '248', nome: 'Freelander' },
        { codigo: '249', nome: 'LR2' },
        { codigo: '250', nome: 'LR3' },
        { codigo: '251', nome: 'LR4' },
        { codigo: '252', nome: 'Range Rover Classic' },
        { codigo: '253', nome: 'Range Rover P38' },
        { codigo: '254', nome: 'Range Rover L322' },
        { codigo: '255', nome: 'Series I' },
        { codigo: '256', nome: 'Series II' },
        { codigo: '257', nome: 'Series III' },
        { codigo: '258', nome: '90' },
        { codigo: '259', nome: '110' },
        { codigo: '260', nome: '130' },
        { codigo: '261', nome: 'Range Rover SV' },
        { codigo: '262', nome: 'Range Rover SVR' },
        { codigo: '263', nome: 'Range Rover Sport SVR' },
        { codigo: '264', nome: 'Defender V8' }
    ],
    '25': [ // Lexus
        { codigo: '251', nome: 'ES' },
        { codigo: '252', nome: 'IS' },
        { codigo: '253', nome: 'LS' },
        { codigo: '254', nome: 'GS' },
        { codigo: '255', nome: 'LC' },
        { codigo: '256', nome: 'RC' },
        { codigo: '257', nome: 'LFA' },
        { codigo: '258', nome: 'UX' },
        { codigo: '259', nome: 'NX' },
        { codigo: '260', nome: 'RX' },
        { codigo: '261', nome: 'GX' },
        { codigo: '262', nome: 'LX' },
        { codigo: '263', nome: 'CT' },
        { codigo: '264', nome: 'HS' },
        { codigo: '265', nome: 'SC' },
        { codigo: '266', nome: 'IS F' },
        { codigo: '267', nome: 'GS F' },
        { codigo: '268', nome: 'RC F' },
        { codigo: '269', nome: 'LC 500' },
        { codigo: '270', nome: 'LS 500' },
        { codigo: '271', nome: 'RX 350' },
        { codigo: '272', nome: 'RX 450h' },
        { codigo: '273', nome: 'NX 200t' },
        { codigo: '274', nome: 'NX 300h' },
        { codigo: '275', nome: 'UX 200' },
        { codigo: '276', nome: 'UX 250h' }
    ],
    '26': [ // Maserati
        { codigo: '261', nome: 'Ghibli' },
        { codigo: '262', nome: 'Quattroporte' },
        { codigo: '263', nome: 'Levante' },
        { codigo: '264', nome: 'Grecale' },
        { codigo: '265', nome: 'MC20' },
        { codigo: '266', nome: 'GranTurismo' },
        { codigo: '267', nome: 'GranCabrio' },
        { codigo: '268', nome: '3200 GT' },
        { codigo: '269', nome: 'Coupe' },
        { codigo: '270', nome: 'Spyder' },
        { codigo: '271', nome: 'Biturbo' },
        { codigo: '272', nome: 'Khamsin' },
        { codigo: '273', nome: 'Bora' },
        { codigo: '274', nome: 'Merak' },
        { codigo: '275', nome: 'Indy' },
        { codigo: '276', nome: 'Mexico' },
        { codigo: '277', nome: 'Sebring' },
        { codigo: '278', nome: '3500 GT' },
        { codigo: '279', nome: '5000 GT' },
        { codigo: '280', nome: 'A6' },
        { codigo: '281', nome: 'A6G' },
        { codigo: '282', nome: 'Tipo 26' },
        { codigo: '283', nome: 'Tipo 61' },
        { codigo: '284', nome: 'Tipo 63' },
        { codigo: '285', nome: 'Tipo 65' }
    ],
    '27': [ // Mazda
        { codigo: '271', nome: 'Mazda3' },
        { codigo: '272', nome: 'Mazda6' },
        { codigo: '273', nome: 'CX-3' },
        { codigo: '274', nome: 'CX-30' },
        { codigo: '275', nome: 'CX-5' },
        { codigo: '276', nome: 'CX-9' },
        { codigo: '277', nome: 'MX-5' },
        { codigo: '278', nome: 'MX-30' },
        { codigo: '279', nome: 'RX-8' },
        { codigo: '280', nome: 'RX-7' },
        { codigo: '281', nome: '323' },
        { codigo: '282', nome: '626' },
        { codigo: '283', nome: '929' },
        { codigo: '284', nome: 'MPV' },
        { codigo: '285', nome: 'B-Series' },
        { codigo: '286', nome: 'Tribute' },
        { codigo: '287', nome: 'Protege' },
        { codigo: '288', nome: 'Millenia' },
        { codigo: '289', nome: 'Xedos' },
        { codigo: '290', nome: 'Eunos' },
        { codigo: '291', nome: 'Atenza' },
        { codigo: '292', nome: 'Axela' },
        { codigo: '293', nome: 'Verisa' },
        { codigo: '294', nome: 'Demio' },
        { codigo: '295', nome: 'Premacy' },
        { codigo: '296', nome: 'Biante' },
        { codigo: '297', nome: 'CX-7' },
        { codigo: '298', nome: 'CX-8' },
        { codigo: '299', nome: 'BT-50' },
        { codigo: '300', nome: 'MX-6' },
        { codigo: '301', nome: 'MX-3' },
        { codigo: '302', nome: '121' },
        { codigo: '303', nome: '2' },
        { codigo: '304', nome: '5' },
        { codigo: '305', nome: '8' }
    ],
    '29': [ // Mini
        { codigo: '291', nome: 'Cooper' },
        { codigo: '292', nome: 'Cooper S' },
        { codigo: '293', nome: 'Cooper SE' },
        { codigo: '294', nome: 'Countryman' },
        { codigo: '295', nome: 'Clubman' },
        { codigo: '296', nome: 'Convertible' },
        { codigo: '297', nome: 'Electric' },
        { codigo: '298', nome: 'John Cooper Works' },
        { codigo: '299', nome: 'One' },
        { codigo: '300', nome: 'Paceman' },
        { codigo: '301', nome: 'Roadster' },
        { codigo: '302', nome: 'Coupe' },
        { codigo: '303', nome: 'Van' },
        { codigo: '304', nome: 'Pickup' },
        { codigo: '305', nome: 'Moke' },
        { codigo: '306', nome: 'Traveller' },
        { codigo: '307', nome: 'Countryman S' },
        { codigo: '308', nome: 'Clubman S' },
        { codigo: '309', nome: 'Cooper D' },
        { codigo: '310', nome: 'Cooper SD' },
        { codigo: '311', nome: 'Countryman SD' },
        { codigo: '312', nome: 'Clubman SD' },
        { codigo: '313', nome: 'Cooper GP' },
        { codigo: '314', nome: 'Cooper S GP' },
        { codigo: '315', nome: 'Cooper Works GP' }
    ],
    '32': [ // Peugeot
        { codigo: '321', nome: '208' },
        { codigo: '322', nome: '308' },
        { codigo: '323', nome: '408' },
        { codigo: '324', nome: '508' },
        { codigo: '325', nome: '2008' },
        { codigo: '326', nome: '3008' },
        { codigo: '327', nome: '5008' },
        { codigo: '328', nome: 'Partner' },
        { codigo: '329', nome: 'Expert' },
        { codigo: '330', nome: 'Boxer' },
        { codigo: '331', nome: '206' },
        { codigo: '332', nome: '207' },
        { codigo: '333', nome: '307' },
        { codigo: '334', nome: '407' },
        { codigo: '335', nome: '607' },
        { codigo: '336', nome: '1007' },
        { codigo: '337', nome: '4007' },
        { codigo: '338', nome: '4008' },
        { codigo: '339', nome: 'RCZ' },
        { codigo: '340', nome: 'iOn' },
        { codigo: '341', nome: 'e-208' },
        { codigo: '342', nome: 'e-2008' },
        { codigo: '343', nome: 'e-308' },
        { codigo: '344', nome: 'e-3008' },
        { codigo: '345', nome: 'e-508' },
        { codigo: '346', nome: 'e-5008' },
        { codigo: '347', nome: 'e-Partner' },
        { codigo: '348', nome: 'e-Expert' },
        { codigo: '349', nome: 'e-Boxer' },
        { codigo: '350', nome: 'e-Rifter' },
        { codigo: '351', nome: 'e-Traveller' },
        { codigo: '352', nome: 'e-3008 GT' },
        { codigo: '353', nome: 'e-508 PSE' },
        { codigo: '354', nome: 'e-208 GT' },
        { codigo: '355', nome: 'e-2008 GT' }
    ],
    '33': [ // Porsche
        { codigo: '331', nome: '911' },
        { codigo: '332', nome: 'Cayman' },
        { codigo: '333', nome: 'Boxster' },
        { codigo: '334', nome: 'Cayenne' },
        { codigo: '335', nome: 'Macan' },
        { codigo: '336', nome: 'Panamera' },
        { codigo: '337', nome: 'Taycan' },
        { codigo: '338', nome: 'Carrera' },
        { codigo: '339', nome: 'Carrera GT' },
        { codigo: '340', nome: '918 Spyder' },
        { codigo: '341', nome: '959' },
        { codigo: '342', nome: '944' },
        { codigo: '343', nome: '928' },
        { codigo: '344', nome: '924' },
        { codigo: '345', nome: '356' },
        { codigo: '346', nome: '550' },
        { codigo: '347', nome: '356 Speedster' },
        { codigo: '348', nome: '550 Spyder' },
        { codigo: '349', nome: '904' },
        { codigo: '350', nome: '906' },
        { codigo: '351', nome: '907' },
        { codigo: '352', nome: '908' },
        { codigo: '353', nome: '909' },
        { codigo: '354', nome: '910' },
        { codigo: '355', nome: '911 GT1' },
        { codigo: '356', nome: '911 GT2' },
        { codigo: '357', nome: '911 GT3' },
        { codigo: '358', nome: '911 GT3 RS' },
        { codigo: '359', nome: '911 Turbo' },
        { codigo: '360', nome: '911 Turbo S' },
        { codigo: '361', nome: 'Cayman GT4' },
        { codigo: '362', nome: 'Boxster Spyder' },
        { codigo: '363', nome: 'Cayenne Turbo' },
        { codigo: '364', nome: 'Macan Turbo' },
        { codigo: '365', nome: 'Panamera Turbo' },
        { codigo: '366', nome: 'Taycan Turbo' },
        { codigo: '367', nome: 'Taycan Turbo S' }
    ],
    '34': [ // Ram
        { codigo: '341', nome: '1500' },
        { codigo: '342', nome: '2500' },
        { codigo: '343', nome: '3500' },
        { codigo: '344', nome: 'ProMaster' },
        { codigo: '345', nome: 'ProMaster City' },
        { codigo: '346', nome: 'C/V' },
        { codigo: '347', nome: 'Dakota' },
        { codigo: '348', nome: 'Durango' },
        { codigo: '349', nome: 'Charger' },
        { codigo: '350', nome: 'Challenger' },
        { codigo: '351', nome: 'Viper' },
        { codigo: '352', nome: 'Neon' },
        { codigo: '353', nome: 'Stratus' },
        { codigo: '354', nome: 'Intrepid' },
        { codigo: '355', nome: 'Stealth' },
        { codigo: '356', nome: 'Avenger' },
        { codigo: '357', nome: 'Caliber' },
        { codigo: '358', nome: 'Nitro' },
        { codigo: '359', nome: 'Magnum' },
        { codigo: '360', nome: 'Caravan' },
        { codigo: '361', nome: 'Shadow' },
        { codigo: '362', nome: 'Spirit' },
        { codigo: '363', nome: 'Lancer' },
        { codigo: '364', nome: 'Colt' },
        { codigo: '365', nome: 'Vista' },
        { codigo: '366', nome: 'Aries' },
        { codigo: '367', nome: 'Reliant' },
        { codigo: '368', nome: 'Omni' },
        { codigo: '369', nome: 'Horizon' },
        { codigo: '370', nome: 'Champ' },
        { codigo: '371', nome: 'Rampage' },
        { codigo: '372', nome: 'Scamp' },
        { codigo: '373', nome: 'Dart' },
        { codigo: '374', nome: 'Valiant' },
        { codigo: '375', nome: 'Barracuda' }
    ],
    '36': [ // Rolls-Royce
        { codigo: '361', nome: 'Phantom' },
        { codigo: '362', nome: 'Ghost' },
        { codigo: '363', nome: 'Wraith' },
        { codigo: '364', nome: 'Dawn' },
        { codigo: '365', nome: 'Cullinan' },
        { codigo: '366', nome: 'Spectre' },
        { codigo: '367', nome: 'Silver Shadow' },
        { codigo: '368', nome: 'Silver Spirit' },
        { codigo: '369', nome: 'Silver Seraph' },
        { codigo: '370', nome: 'Corniche' },
        { codigo: '371', nome: 'Camargue' },
        { codigo: '372', nome: 'Silver Cloud' },
        { codigo: '373', nome: 'Silver Dawn' },
        { codigo: '374', nome: 'Silver Wraith' },
        { codigo: '375', nome: 'Silver Ghost' },
        { codigo: '376', nome: 'Phantom I' },
        { codigo: '377', nome: 'Phantom II' },
        { codigo: '378', nome: 'Phantom III' },
        { codigo: '379', nome: 'Phantom IV' },
        { codigo: '380', nome: 'Phantom V' },
        { codigo: '381', nome: 'Phantom VI' },
        { codigo: '382', nome: 'Phantom VII' },
        { codigo: '383', nome: 'Phantom VIII' },
        { codigo: '384', nome: 'Ghost Series I' },
        { codigo: '385', nome: 'Ghost Series II' },
        { codigo: '386', nome: 'Wraith Black Badge' },
        { codigo: '387', nome: 'Dawn Black Badge' },
        { codigo: '388', nome: 'Cullinan Black Badge' },
        { codigo: '389', nome: 'Phantom Black Badge' },
        { codigo: '390', nome: 'Ghost Black Badge' }
    ],
    '41': [ // Volvo
        { codigo: '411', nome: 'S60' },
        { codigo: '412', nome: 'S90' },
        { codigo: '413', nome: 'V60' },
        { codigo: '414', nome: 'V90' },
        { codigo: '415', nome: 'XC40' },
        { codigo: '416', nome: 'XC60' },
        { codigo: '417', nome: 'XC90' },
        { codigo: '418', nome: 'C40' },
        { codigo: '419', nome: 'S40' },
        { codigo: '420', nome: 'S80' },
        { codigo: '421', nome: 'V40' },
        { codigo: '422', nome: 'V70' },
        { codigo: '423', nome: 'C30' },
        { codigo: '424', nome: 'C70' },
        { codigo: '425', nome: '850' },
        { codigo: '426', nome: '940' },
        { codigo: '427', nome: '960' },
        { codigo: '428', nome: '240' },
        { codigo: '429', nome: '260' },
        { codigo: '430', nome: '740' },
        { codigo: '431', nome: '760' },
        { codigo: '432', nome: '780' },
        { codigo: '433', nome: '140' },
        { codigo: '434', nome: '164' },
        { codigo: '435', nome: '1800' },
        { codigo: '436', nome: 'P1800' },
        { codigo: '437', nome: 'P1900' },
        { codigo: '438', nome: 'PV444' },
        { codigo: '439', nome: 'PV544' },
        { codigo: '440', nome: 'PV36' },
        { codigo: '441', nome: 'PV51' },
        { codigo: '442', nome: 'PV52' },
        { codigo: '443', nome: 'PV53' },
        { codigo: '444', nome: 'PV54' },
        { codigo: '445', nome: 'PV55' },
        { codigo: '446', nome: 'PV56' },
        { codigo: '447', nome: 'PV57' },
        { codigo: '448', nome: 'PV58' },
        { codigo: '449', nome: 'PV59' },
        { codigo: '450', nome: 'PV60' },
        { codigo: '451', nome: 'PV61' },
        { codigo: '452', nome: 'PV62' },
        { codigo: '453', nome: 'PV63' },
        { codigo: '454', nome: 'PV64' },
        { codigo: '455', nome: 'PV65' },
        { codigo: '456', nome: 'PV66' },
        { codigo: '457', nome: 'PV67' },
        { codigo: '458', nome: 'PV68' },
        { codigo: '459', nome: 'PV69' },
        { codigo: '460', nome: 'PV70' }
    ]
};

export const MOCK_YEARS: MockYear[] = [
    { codigo: '2024', nome: '2024' },
    { codigo: '2023', nome: '2023' },
    { codigo: '2022', nome: '2022' },
    { codigo: '2021', nome: '2021' },
    { codigo: '2020', nome: '2020' },
    { codigo: '2019', nome: '2019' },
    { codigo: '2018', nome: '2018' },
    { codigo: '2017', nome: '2017' },
    { codigo: '2016', nome: '2016' },
    { codigo: '2015', nome: '2015' },
    { codigo: '2014', nome: '2014' },
    { codigo: '2013', nome: '2013' },
    { codigo: '2012', nome: '2012' },
    { codigo: '2011', nome: '2011' },
    { codigo: '2010', nome: '2010' },
    { codigo: '2009', nome: '2009' },
    { codigo: '2008', nome: '2008' },
    { codigo: '2007', nome: '2007' },
    { codigo: '2006', nome: '2006' },
    { codigo: '2005', nome: '2005' },
    { codigo: '2004', nome: '2004' },
    { codigo: '2003', nome: '2003' },
    { codigo: '2002', nome: '2002' },
    { codigo: '2001', nome: '2001' },
    { codigo: '2000', nome: '2000' }
];

// Funções helper para simular delay de rede
export const simulateNetworkDelay = (ms: number = 100) => {
    return new Promise(resolve => setTimeout(resolve, ms));
};

// Funções mockadas para uso como fallback
export const getMockBrands = async (): Promise<MockBrand[]> => {
    await simulateNetworkDelay(100);
    return MOCK_BRANDS;
};

export const getMockModels = async (brandCode: string): Promise<MockModel[]> => {
    await simulateNetworkDelay(150);
    return MOCK_MODELS[brandCode] || [];
};

export const getMockYears = async (brandCode: string, modelCode: string): Promise<MockYear[]> => {
    await simulateNetworkDelay(100);
    return MOCK_YEARS;
}; 